# Generated by Django 3.2.7 on 2022-05-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsale', '0002_sale_car_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_acc_details',
        ),
        migrations.DeleteModel(
            name='sale_car_details',
        ),
    ]
