# Generated by Django 3.2.7 on 2022-05-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsale', '0005_sale_car_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(max_length=200)),
                ('buyer_address', models.CharField(max_length=200)),
                ('buyer_pincode', models.CharField(max_length=200)),
                ('buyer_time', models.CharField(max_length=500)),
                ('buser_name', models.CharField(max_length=200)),
                ('bcar_state', models.CharField(max_length=200)),
                ('buser_phoneno', models.CharField(max_length=50)),
                ('bcar_model_name', models.CharField(max_length=200)),
                ('bcar_brand', models.CharField(max_length=200)),
                ('bcar_image', models.CharField(max_length=500)),
                ('bcar_price', models.CharField(max_length=200)),
                ('byear', models.CharField(max_length=200)),
                ('bseller_type', models.CharField(max_length=200)),
                ('bkm_driven', models.CharField(max_length=200)),
                ('bowner_type', models.CharField(max_length=200)),
                ('bfuel_type', models.CharField(max_length=200)),
                ('btransmission_type', models.CharField(max_length=200)),
                ('bmileage', models.CharField(max_length=200)),
                ('bengine', models.CharField(max_length=200)),
                ('bmax_power', models.CharField(max_length=200)),
                ('bseats', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'buyer_booking_details',
            },
        ),
    ]
