# Generated by Django 3.2.7 on 2022-05-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsale', '0007_delete_sale_car_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='sale_car_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('car_state', models.CharField(max_length=200)),
                ('user_phoneno', models.CharField(max_length=50)),
                ('car_model_name', models.CharField(max_length=200)),
                ('car_brand', models.CharField(max_length=200)),
                ('car_image', models.CharField(max_length=500)),
                ('car_price', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('seller_type', models.CharField(max_length=200)),
                ('km_driven', models.CharField(max_length=200)),
                ('owner_type', models.CharField(max_length=200)),
                ('fuel_type', models.CharField(max_length=200)),
                ('transmission_type', models.CharField(max_length=200)),
                ('mileage', models.CharField(max_length=200)),
                ('engine', models.CharField(max_length=200)),
                ('max_power', models.CharField(max_length=200)),
                ('seats', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'sale_car_details',
            },
        ),
    ]
