from django.urls import path
from . import views
urlpatterns = [
	path('create_acc',views.create_acc),
	path('account_created',views.account_created),
	path('showaccountdb',views.showaccountdb),
	path('delete_acc/<int:id>',views.delete_acc),
	path('edit_create_acc/<int:id>',views.edit_create_acc),
	path('create_acc_edit/<int:id>',views.create_acc_edit),
	path('welcomeboss',views.welcomeboss),
	path('login_acc',views.login_acc),
	path('loginsuccess',views.loginsuccess),
	path('uploadcar',views.uploadcar),
	path('car_details_filled',views.car_details_filled),
	path('showcardb',views.showcardb),
	path('deletecardb/<int:id>',views.deletecardb),
	path('editcardb/<int:id>',views.editcardb),
	path('caredited/<int:id>',views.caredited),
	path('showcarmain',views.showcarmain),
	path('viewcarfeatures/<int:id>',views.viewcarfeatures),
	path('admin_login',views.admin_login),
	path('admin_login_success',views.admin_login_success),
	path('buyerbooking/<int:id>',views.buyerbooking),
	path('buyercar/<int:id>',views.buyercar),
	path('buyerordered',views.buyerordered),
	path('printbill/<int:id>',views.printbill),
	path('finalbooking',views.finalbooking),
	path('showbuyerdb',views.showbuyerdb),
	path('finalupload',views.finalupload),
	path('startpage',views.startpage),
]